### ISSUE TITLE
3x1x3 interleaved layout returns y().stride() of 1 instead of 9

### ISSUE THREAD

**Issue by scribbleink** [dsharlet/array#91]
Hi Dillon 👋

Hope you're doing well.

Ran into a bug today that I'd like to share with you.

Creating a `3x1x3` interleaved shape and querying the `y().stride()` returns `1` instead of `9`. I believe it is fine for the stride to not be well-defined in terms of the design assumptions, but when the stride is used to calculate number of bytes per row, it becomes problematic.

This can be triggered by wrapping it in a non-owning view such as OpenCV `cv::Mat` which checks against a minimum step size (https://github.com/opencv/opencv/blob/4.x/modules/core/src/matrix.cpp#L434) and fails.

Use cases for 1px height images include LUTs and unit tests.

For OpenCV we can work around it by updating those specific wrappers to test for `height == 1` at run-time and switch to a different logic for the number of bytes per row, or even algorithmically by allocating an extra row that will not be used, but more generally it seems undesirable for clients of the array library to have to work around it and I was wondering if there's something we can to do address this within the library.

**Comment by dsharlet** [comment]
I think this is the same problem as here: https://github.com/dsharlet/array/blob/master/test/shape.cpp#L184

This has come up before in other contexts too. The problem is that when the extent is 1, there's no real constraint on the stride, so the automatic stride algorithm just gives it something that seems reasonable to it. I think this is hard to fix without baking some crappy heuristic into the algorithm. @fbleibel-g might have more information about those other contexts he can share with you.

**Comment by benweiss** [comment]
Hi Dillon,

I tried adding a few lines to solve this issue, and it seems to work. In 'is_stride_ok() in array.h', I did the following (inserted the middle 'if()' block):

```
if (is_unresolved(dim.stride())) {
  // If the dimension has an unknown stride, it's OK, we're
  // resolving the current dim first.
  return true;
}
if (extent == 1 && abs(stride) == abs(dim.stride()) && dim.extent() > 1) {
  // Special-cases "extent == 1" to avoid unexpectedly giving a stride of 1 for
  // outer dimensions; e.g. the y-stride for single-row interleaved images, or
  // the plane-stride for single-plane Planar images.
  return false;
}
if (dim.extent() * abs(dim.stride()) <= stride) {
  // The dim is completely inside the proposed stride.
  return true;
}
```

This "fixes" the cases mentioned. It also enables the commented-out test you mentioned above. Curious what you think? If it looks ok, I can submit it as a PR, or feel free to incorporate it.

Thanks,
Ben

**Comment by dsharlet** [comment]
Hmm, that is a lot less crufty than I thought would be necessary.

I played around with this a bit and added some more tests to see what it does in these cases: 
```
  // Stride one dimensions mixed in with extent 1 dimensions.
  check_resolved_strides<3>({1, 1, {0, 2, 1}}, {2, 2, 1});
  check_resolved_strides<3>({1, {0, 2, 1}, 1}, {2, 1, 2});
  check_resolved_strides<3>({1, 10, {0, 2, 1}}, {2, 2, 1});
  check_resolved_strides<3>({5, {0, 2, 1}, 1}, {2, 1, 10});
```

It does produce reasonable results in these cases.

I think you should send it as a PR (with the extra tests above), this is a really nice improvement.

**Comment by benweiss** [comment]
Thanks Dillon, I've sent a PR with my changes and your added tests. Let me know if it needs a CLA.

The only non-obvious side effect I've encountered from this change is that it is no longer possible to implicitly cast between interleaved and planar single-channel images, since the channel strides now differ. Probably this is a good thing; it's most likely a bug if anyone's code was trying to do that. But the assertion it triggers could trivially be modified to still allow it, if there were any reason to.
